---
title: "Figures_paper"
author: "Andres Baeza"
date: "July 5, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Read USA map
```{r}

#require(USAboundaries)
require(raster)
USA_map_full<-maptools::readShapeSpatial("C:/Users/abaezaca/Dropbox (ASU)/Design Principles in CIS/maps_USA/tl_2017_us_state/tl_2017_us_state")
top = 49.3457868 # north lat
left = -124.7844079 # west long
right = -66.9513812 # east long
bottom =  24.7433195 # south lat
USA_map<-raster::crop(USA_map_full,raster::extent(left,right,bottom,top))
USA_map@data$NAME<-factor(USA_map@data$NAME)
rm(USA_map_full)
```


Figure 1: past and current precence of _P. glandulosa_

```{r}
load("data/Prosopis_glandulosa_presence_data")#presence data
load("data/PresencesNotUsed_obj")#presences_NotUsed
require(raster)
#load climate variables
predictors_past <- get_past_climate()
predictors_present <- get_current_climate()
predictors_future <- get_future_climate()

predictors_future <- resample(predictors_future,predictors_present)
############################################################################

llmespg_H<-cbind(mesquite_pg_clean$lon[which(mesquite_pg_clean$year<1950)], mesquite_pg_clean$lat[which(mesquite_pg_clean$year<1950)])
presvals_pg_H<-as.data.frame(raster::extract(predictors_past, llmespg_H))

presences_NotUsed_H=llmespg_H[-which(presvals_pg_H$mean_annual_temperature>0),]
llmespg_H=llmespg_H[which(presvals_pg_H$mean_annual_temperature>0),]

llmespg_C<-cbind(mesquite_pg_clean$lon[which(mesquite_pg_clean$year>1950)], mesquite_pg_clean$lat[which(mesquite_pg_clean$year>1950)])

presvals_pg_C<-as.data.frame(raster::extract(predictors_past, llmespg_C))
llmespg_C=llmespg_C[which(presvals_pg_C$mean_annual_temperature>0),]



#llmespg_C<-llmespg_C[,-which(llmespg_C[,2]<0)]
#llmespg_H<-llmespg_H[,-which(llmespg_H[,2]<0)]

png(filename = "output_maps/figure1.png",width = 26,height = 8,units = "cm",res = 300)

par(mfrow=c(1,2),mar=c(4,4,3,3))

#maps::map("usa",fill = T,col="grey")
#box(which = "plot")
image(predictors_past[[2]],zlim=c(-17,30),  col ="white",  xlab = 'Longitude', ylab = 'Latitude',main="a. Presences before 1950")
plot(USA_map,add=T)
points(llmespg_H[,1],llmespg_H[,2],col="darkorchid4",pch=20,cex=0.1)
#legend(x=-120,y=54,legend = "a. Presences before 1950",col = "white",bty = "n",pch =20,cex=0.6)


#maps::map("usa",fill = T,col="grey")
#box(which = "plot")
image(predictors_past[[2]],zlim=c(-17,30),  col ="white",  xlab = 'Longitude', ylab = '',main="b. Presences after 1950")
plot(USA_map,add=T)
points(llmespg_C[,1],llmespg_C[,2],col="darkorchid4",pch=20,cex=0.1)

#legend(x=-120,y=54,legend = "b. Presences after 1950",col = "white",bty = "n",pch =20,cex=0.6)

dev.off()


```



Figure 2: past present and future climate 
```{r,cache=TRUE}
#figure 1
png(filename = "output_maps/figure2.png",width = 30,height = 22,units = "cm",res = 300)

par(mfrow=c(3,3))
#Temperature
image(predictors_past[[1]],zlim=c(-11,30),  col = rev(RColorBrewer::brewer.pal(9, "RdYlBu")),  xlab = 'Longitude', ylab = 'Latitude', main = 'a.  Ave. daily Temp. [1900-1950]',breaks=c(-11,-5,0,5,10,15,20,25,30,100))
plot(USA_map,add=T)

image(mask(predictors_present[[1]],USA_map),zlim=c(-11,30),  col = rev(RColorBrewer::brewer.pal(9, "RdYlBu")),  xlab = 'Longitude', ylab = 'Latitude', main = 'b. [1951-2000]',breaks=c(-11,-5,0,5,10,15,20,25,30,100))
plot(USA_map,add=T)

image(mask(predictors_future[[1]],USA_map),zlim=c(-11,30),  col = rev(RColorBrewer::brewer.pal(9, "RdYlBu")),  xlab = 'Longitude', ylab = 'Latitude', main = 'c.   [2080-2010]',breaks=c(-11,-5,0,5,10,15,20,25,30,100))
plot(USA_map,add=T)


image(predictors_past[[3]],zlim=c(-17,30),  col = rev(RColorBrewer::brewer.pal(9, "RdYlBu")),  xlab = 'Longitude', ylab = 'Latitude', main = 'd.  Min. winter daily Temp. [1900-1950]',breaks=c(-17,-5,0,5,10,15,20,25,30,100))
plot(USA_map,add=T)

image(mask(predictors_present[[3]],USA_map),zlim=c(-17,30),  col = rev(RColorBrewer::brewer.pal(9, "RdYlBu")),  xlab = 'Longitude', ylab = 'Latitude', main = 'e. [1951-2000]',breaks=c(-17,-5,0,5,10,15,20,25,30,100))
plot(USA_map,add=T)

image(mask(predictors_future[[3]],USA_map),zlim=c(-17,30),  col = rev(RColorBrewer::brewer.pal(9, "RdYlBu")),  xlab = 'Longitude', ylab = 'Latitude', main = 'f.  [2080-2010]',breaks=c(-17,-5,0,5,10,15,20,25,30,100))
plot(USA_map,add=T)


#precipitation
image(predictors_past[[4]],zlim=c(0,16),  col = RColorBrewer::brewer.pal(9, "YlGn"),  xlab = 'Longitude', ylab = 'Latitude', main = 'g. Ave. daily Rainfall [1900-1950]',breaks=c(0,1,2,3,4,5,6,7,20,100))
plot(USA_map,add=T)

image(mask(predictors_present[[4]],USA_map),zlim=c(0,16),  col = RColorBrewer::brewer.pal(9, "YlGn"),  xlab = 'Longitude', ylab = 'Latitude', main = 'h.  [1950-2000]',breaks=c(0,1,2,3,4,5,6,7,20,100))
plot(USA_map,add=T)

image(mask(predictors_future[[4]],USA_map),zlim=c(0,16),  col = RColorBrewer::brewer.pal(9, "YlGn"),  xlab = 'Longitude', ylab = 'Latitude', main = 'i. 2080-2100',breaks=c(0,1,2,3,4,5,6,7,20,100))
plot(USA_map,add=T)

dev.off()

```




Figure 3
```{R}
Met="AllMethods"
#maps_present<-estimation_present(estimation_method = Met)

#maps_past<-estimation_past(estimation_method = Met)

maps<-combined_distribution()

maps_past <- maps[[1]]
maps_present <- maps[[2]]

#maps_present=resample(maps_present,maps_past)

png(filename = paste(paste("output_maps/",Met,sep = ""),"_Figure3.png"),
    width = 60,
    height = 30,
    units = "cm",
    res = 200)
par(mfrow=c(2,3),cex=1.2)

image(maps_past[[1]]>0.5,col=c("grey",RColorBrewer::brewer.pal(9, "YlOrRd")[9]),ylab="Latitude",xlab="Longitude",main="a.     P50")
plot(USA_map,add=T)

image(maps_past[[2]]>0.5,col=c("grey",RColorBrewer::brewer.pal(9, "YlOrRd")[9]),ylab="Latitude",xlab="Longitude",main="b.     P2000")
plot(USA_map,add=T)

image(maps_past[[3]]>0.5,col=c("grey",RColorBrewer::brewer.pal(9, "YlOrRd")[9]),ylab="Latitude",xlab="Longitude",main="c.     P2100")
plot(USA_map,add=T)

image(maps_present[[1]]>0.5,col=c("grey",RColorBrewer::brewer.pal(9, "YlOrRd")[9]),ylab="Latitude",xlab="Longitude",main="d.     R2000")
plot(USA_map,add=T)

image(maps_present[[1]]>0.5,col=c("grey",RColorBrewer::brewer.pal(9, "YlOrRd")[9]),ylab="Latitude",xlab="Longitude",main="d.     R2000")
plot(USA_map,add=T)

image(maps_present[[2]]>0.5,col=c("grey",RColorBrewer::brewer.pal(9, "YlOrRd")[9]),ylab="Latitude",xlab="Longitude",main="e.     R2100")
plot(USA_map,add=T)

dev.off()
##Raster operations

```


Figure 4
```{r,cache=TRUE}

######################################################
#Figure##########################################
###################################################


Diff_T50T2000=(maps_past[[2]]>0.5)-(maps_past[[1]]>0.5) #current expansion due to climate
Diff_P2000T2000=(maps_present[[1]]>0.5) - (maps_past[[2]]>0.5)  # P2000- T2000 current expasion due to Land-use change

DiffP2000_T50= (Diff_T50T2000>0.5) + (Diff_P2000T2000 > 0.5)
#  (maps_present[[1]]>0.5) - (maps_past[[1]]>0.5) #P2000_F - T50   #total current expansion


#Diff_T50T2100=(T2100>0)-T50 #future expansion due to climate
Diff_T2100P2000=(maps_past[[3]]>0.5) - (maps_present[[1]]>0.5) 


DiffP2100_T2100=(maps_present[[2]]>0.5) - (maps_past[[3]]>0.5)#future expansion due to LU 

DiffP2100_P2000=(Diff_T2100P2000>0.5)+(DiffP2100_T2100>0.5)
#  (maps_present[[2]]>0.5) - (maps_present[[1]]>0.5)#P2100_F - P2000_F #Total expansion due to climate and LU



png(filename = paste(paste("output_maps/",Met,sep=""),"_figure4.png",sep=""),width = 60,height = 30,units = "cm",res = 200)
par(mfrow=c(2,3),cex=1.2)

image(Diff_T50T2000>0.5,col=c("grey","darkgreen"),ylab="Lat.",xlab="Long.",main="A)   Current [C]")
plot(USA_map,add=T)

image(Diff_P2000T2000>0,col=c("grey","yellow"),ylab="Lat.",xlab="Long.",main="B)    Current [LU]")
plot(USA_map,add=T)

image((DiffP2000_T50==1),col=c("grey","red"),ylab="Lat.",xlab="Long.",main="C)   Current [C + LU]")
plot(USA_map,add=T)

image(Diff_T2100P2000>0.5,col=c("grey","darkgreen"),ylab="Lat.",xlab="Long.",main="D)   Future [C]")
plot(USA_map,add=T)

image(DiffP2100_T2100>0.5,col=c("grey","yellow"),ylab="Lat.",xlab="Long.",main="E)   Future [LU]")
plot(USA_map,add=T)

image((DiffP2100_P2000==1),col=c("grey","red"),ylab="Lat.",xlab="Long.",main="F)   Future [C + LU]")
plot(USA_map,add=T)
dev.off()


```


####extract area by state and create a csv value file
```{r,cache=TRUE}
A=raster::area(Diff_T50T2000)
Current_expansion_climate_area= raster::extract((A*(Diff_T50T2000>0)),USA_map,fun=sum)

Current_expansion_LU_area= raster::extract((A*(Diff_P2000T2000>0)),USA_map,fun=sum)

Current_expansion_LU_C_area= raster::extract((A*(DiffP2000_T50>0)),USA_map,fun=sum)

Future_expansion_climate_area= raster::extract((A*(Diff_T2100P2000>0)),USA_map,fun=sum)

Future_expansion_LU_area= raster::extract((A*(DiffP2100_T2100>0)),USA_map,fun=sum)

Future_expansion_LU_C_area= raster::extract((A*(DiffP2100_P2000>0)),USA_map,fun=sum)


area_perState=cbind(Current_expansion_climate_area,
Current_expansion_LU_area,
Current_expansion_LU_C_area,
Future_expansion_climate_area,
Future_expansion_LU_area,
Future_expansion_LU_C_area)

area_perState<-as.data.frame((area_perState))
rownames(area_perState)<-USA_map$NAME
colnames(area_perState)=c("C_C","C_LU","C_C_LU","F_C","F_LU","F_C_LU")
View(area_perState)
write.csv(area_perState,file = "table_expansion_AreabyState.csv")
#area_perState=read.csv("table_expansion_AreabyState.csv")
#area_perState$X<-USA_map$NAME
```




# Calculate total area (in km2) for the predicted distributions T50, T2000, T2100, P2000, and P2100.

```{R}
A=area(Diff_T50T2000)

P50_area= cellStats(A*(maps_past[[1]]>0),stat ="sum")

P2000_area= cellStats(A*(maps_past[[2]]>0),stat ="sum")

P2100_area= cellStats(A*(maps_past[[3]]>0),stat ="sum")

R2000_area= cellStats(A*maps_present[[1]],stat ="sum")

R2100_area= cellStats(A*maps_present[[2]],stat ="sum")

area_table=data.frame(matrix(data = c(P50_area,P2000_area,P2100_area,NA,R2000_area,R2100_area),nrow = 2,ncol = 3,byrow = T))
View(area_table)
colnames(area_table)<-c("Past Climate","Recent Climate","Future Climate")
rownames(area_table)<-c("Model P","Model R")
write.csv(x = area_table,file = "area_table_in_kmsquared.csv")
```
