---
title: "historical_analysis"
author: "Andres Baeza"
date: "April 3, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Historical Analysis of prosopis glandulosa distribution using monthy average rainfall from 1900-1950

## generate an interpolated grid to be use in the niche model


```{r}
library(ggplot2)
library(gstat)
library(sp)
library(maptools)
```

Rainfall Interpolation historic
```{r}
load('monlthy_precipitation_By_station_obj')
precip2=precip
load('monlthy_precipitation_By_station_obj_2')
precip2=rbind(precip2,precip)
precip2=unique(precip2)


USA_map_full<-maptools::readShapeSpatial("C:/Users/abaezaca/Dropbox (ASU)/Design Principles in CIS/maps_USA/tl_2017_us_state/tl_2017_us_state")
load("PTT_stack_obj")

left=extent(PTT_stack)[1]
right=extent(PTT_stack)[2]
top=extent(PTT_stack)[4]
bottom=extent(PTT_stack)[3]

USA_map<-raster::crop(USA_map_full,raster::extent(left,right,bottom,top))
USA_map@data$NAME<-factor(USA_map@data$NAME)

x.range <- as.numeric(c(left, right))  # min/max longitude of the interpolation area
y.range <- as.numeric(c(bottom, top))  # min/max latitude of the interpolation area
grd <- expand.grid(x = seq(from = x.range[1], to = x.range[2], length.out =  PTT_stack@ncols), y = seq(from = y.range[1], 
    to = y.range[2], length.out = PTT_stack@nrows))  # expand points to grid
coordinates(precip2) = ~long + Lat
coordinates(grd) <- ~x + y
gridded(grd) <- TRUE

idw_j<-gstat::idw(tp~1,locations=subset(precip2,month==1),newdata=grd)
idw_j<-raster(idw_j)
idw_f<-gstat::idw(tp~1,locations=subset(precip2,month==2),newdata=grd)
idw_f<-raster(idw_f)
idw_m<-gstat::idw(tp~1,locations=subset(precip2,month==3),newdata=grd)
idw_m<-raster(idw_m)
idw_a<-gstat::idw(tp~1,locations=subset(precip2,month==4),newdata=grd)
idw_a<-raster(idw_a)
idw_ma<-gstat::idw(tp~1,locations=subset(precip2,month==5),newdata=grd)
idw_ma<-raster(idw_ma)
idw_ju<-gstat::idw(tp~1,locations=subset(precip2,month==6),newdata=grd)
idw_ju<-raster(idw_ju)
idw_jl<-gstat::idw(tp~1,locations=subset(precip2,month==7),newdata=grd)
idw_jl<-raster(idw_jl)
idw_au<-gstat::idw(tp~1,locations=subset(precip2,month==8),newdata=grd)
idw_au<-raster(idw_au)
idw_s<-gstat::idw(tp~1,locations=subset(precip2,month==9),newdata=grd)
idw_s<-raster(idw_s)
idw_o<-gstat::idw(tp~1,locations=subset(precip2,month==10),newdata=grd)
idw_o<-raster(idw_o)
idw_n<-gstat::idw(tp~1,locations=subset(precip2,month==11),newdata=grd)
idw_n<-raster(idw_n)
idw_d<-gstat::idw(tp~1,locations=subset(precip2,month==12),newdata=grd)
idw_d<-raster(idw_d)
stack_PPT_histor=stack(idw_j,
                       idw_f,
                       idw_m,
                       idw_a,
                       idw_ma,
                       idw_ju,
                       idw_jl,
                       idw_au,
                       idw_s,
                       idw_o,
                       idw_n,
                       idw_d
                       )
save(stack_PPT_histor,file="stack_PPT_historico")
##############################################################
#Rainfall Interpolation current
load("monlthy_precipitation_1950_2000_By_station_obj")
precip2=precip
load("monlthy_precipitation_1950_2000_By_station_objB")
precip2=rbind(precip2,precip)
load("monlthy_precipitation_1950_2000_By_station_objC")
precip2=rbind(precip2,precip)
load("monlthy_precipitation_1950_2000_By_station_objD")
precip2=rbind(precip2,precip)
load("monlthy_precipitation_1950_2000_By_station_objE")
precip2=rbind(precip2,precip)
load("monlthy_precipitation_1950_2000_By_station_objF")
precip2=rbind(precip2,precip)
load("monlthy_precipitation_1950_2000_By_station_objG")
precip2=rbind(precip2,precip)
precip2=unique(precip2)
precip3=cbind(precip2,rep(seq(1,5027,1),each=12))
colnames(precip3)[5]="station"
pp2<-aggregate( tp  ~ station, data=precip3, FUN=sum,simplify=F)


pp3=as.data.frame(cbind(subset(precip2,month==1)$long,subset(precip2,month==1)$Lat,as.vector(unlist(pp2$tp))))
colnames(pp3)=c("long","Lat","tp")

USA_map_full<-maptools::readShapeSpatial("C:/Users/abaezaca/Dropbox (ASU)/Design Principles in CIS/maps_USA/tl_2017_us_state/tl_2017_us_state")
load("PTT_stack_obj")

left=extent(PTT_stack)[1]
right=extent(PTT_stack)[2]
top=extent(PTT_stack)[4]
bottom=extent(PTT_stack)[3]

USA_map<-raster::crop(USA_map_full,raster::extent(left,right,bottom,top))
USA_map@data$NAME<-factor(USA_map@data$NAME)

x.range <- as.numeric(c(left, right))  # min/max longitude of the interpolation area
y.range <- as.numeric(c(bottom, top))  # min/max latitude of the interpolation area
grd <- expand.grid(x = seq(from = x.range[1], to = x.range[2], length.out =  PTT_stack@ncols), y = seq(from = y.range[1], 
    to = y.range[2], length.out = PTT_stack@nrows))  # expand points to grid
coordinates(pp3) = ~long + Lat
coordinates(grd) <- ~x + y
gridded(grd) <- TRUE


idw_annualPPT<-gstat::idw(tp ~ 1,locations=pp3,newdata=grd)
raster_annualPPT<-raster(idw_annualPPT)/10
save(raster_annualPPT,file="annual_total_rainfall_raster_current")

idw_j<-raster(idw_annualPPT)

idw_j<-gstat::idw(tp~1,locations=subset(precip2,month==1),newdata=grd)
idw_j<-raster(idw_j)
idw_f<-gstat::idw(tp~1,locations=subset(precip2,month==2),newdata=grd)
idw_f<-raster(idw_f)
idw_m<-gstat::idw(tp~1,locations=subset(precip2,month==3),newdata=grd)
idw_m<-raster(idw_m)
idw_a<-gstat::idw(tp~1,locations=subset(precip2,month==4),newdata=grd)
idw_a<-raster(idw_a)
idw_ma<-gstat::idw(tp~1,locations=subset(precip2,month==5),newdata=grd)
idw_ma<-raster(idw_ma)
idw_ju<-gstat::idw(tp~1,locations=subset(precip2,month==6),newdata=grd)
idw_ju<-raster(idw_ju)
idw_jl<-gstat::idw(tp~1,locations=subset(precip2,month==7),newdata=grd)
idw_jl<-raster(idw_jl)
idw_au<-gstat::idw(tp~1,locations=subset(precip2,month==8),newdata=grd)
idw_au<-raster(idw_au)
idw_s<-gstat::idw(tp~1,locations=subset(precip2,month==9),newdata=grd)
idw_s<-raster(idw_s)
idw_o<-gstat::idw(tp~1,locations=subset(precip2,month==10),newdata=grd)
idw_o<-raster(idw_o)
idw_n<-gstat::idw(tp~1,locations=subset(precip2,month==11),newdata=grd)
idw_n<-raster(idw_n)
idw_d<-gstat::idw(tp~1,locations=subset(precip2,month==12),newdata=grd)
idw_d<-raster(idw_d)
stack_PPT=stack(idw_j,
                       idw_f,
                       idw_m,
                       idw_a,
                       idw_ma,
                       idw_ju,
                       idw_jl,
                       idw_au,
                       idw_s,
                       idw_o,
                       idw_n,
                       idw_d
                       )
save(stack_PPT,file="stack_PPT_current")
##############################################################

#Min. Temperature Interpolation
load('monthly_Tmin_By_station_obj')
Tmin_o=Tmin
load('monthly_Tmin_By_station_obj2')
Tmin_o=rbind(Tmin_o,Tmin)
load('monthly_Tmin_By_station_obj3')
Tmin_o=rbind(Tmin_o,Tmin)
load('monthly_Tmin_By_station_obj4')
Tmin_o=rbind(Tmin_o,Tmin)
load('monthly_Tmin_By_station_obj5')
Tmin_o=rbind(Tmin_o,Tmin)
Tmin_o=unique(Tmin_o)
coordinates(Tmin_o) = ~long + Lat

idw_j<-gstat::idw(tp~1,locations=subset(Tmin_o,month==1),newdata=grd)
idw_j <-raster(idw_j)
idw_f<-gstat::idw(tp~1,locations=subset(Tmin_o,month==2),newdata=grd)
idw_f <-raster(idw_f)
idw_m<-gstat::idw(tp~1,locations=subset(Tmin_o,month==3),newdata=grd)
idw_m <-raster(idw_m)
idw_a<-gstat::idw(tp~1,locations=subset(Tmin_o,month==4),newdata=grd)
idw_a <-raster(idw_a)
idw_ma<-gstat::idw(tp~1,locations=subset(Tmin_o,month==5),newdata=grd)
idw_ma <-raster(idw_ma)
idw_ju<-gstat::idw(tp~1,locations=subset(Tmin_o,month==6),newdata=grd)
idw_ju <-raster(idw_ju)
idw_jl<-gstat::idw(tp~1,locations=subset(Tmin_o,month==7),newdata=grd)
idw_jl <-raster(idw_jl)
idw_au<-gstat::idw(tp~1,locations=subset(Tmin_o,month==8),newdata=grd)
idw_au <-raster(idw_au)
idw_s<-gstat::idw(tp~1,locations=subset(Tmin_o,month==9),newdata=grd)
idw_s <-raster(idw_s)
idw_o<-gstat::idw(tp~1,locations=subset(Tmin_o,month==10),newdata=grd)
idw_o <-raster(idw_o)
idw_n<-gstat::idw(tp~1,locations=subset(Tmin_o,month==11),newdata=grd)
idw_n <-raster(idw_n)
idw_d<-gstat::idw(tp~1,locations=subset(Tmin_o,month==12),newdata=grd)
idw_d <-raster(idw_d)
stack_Tmin_histor=stack(idw_j,
                       idw_f,
                       idw_m,
                       idw_a,
                       idw_ma,
                       idw_ju,
                       idw_jl,
                       idw_au,
                       idw_s,
                       idw_o,
                       idw_n,
                       idw_d
                       )

save(stack_Tmin_histor,file="stack_Tmin_historico")
###########################################################################
#Max. and mean Temperature Interpolation
#load("monthly_Tmean_1900_1950_By_station_obj")
load("monthly_Tmean_1950_2000_By_station_obj")
Tmean2=as.data.frame(cbind(Tmean,rep(seq(1,dim(Tmean)[1]/12,1),each=12)))
colnames(Tmean2)[5]="station"
#Tmean=Tmean[-which(is.na(Tmean$tmean)),]

T2<-aggregate(tmean  ~ station, data=Tmean2,FUN=mean,simplify=F)


T3=as.data.frame(cbind(subset(Tmean,month==1)$long[-length(subset(Tmean,month==1)$long)],subset(Tmean,month==1)$Lat[-length(subset(Tmean,month==1)$Lat)],as.vector(unlist(T2$tmean))))
colnames(T3)=c("long","Lat","tm")

coordinates(T3)= ~long + Lat
idw_Tmean_annual<-gstat::idw(tm~1,locations=T3,newdata=grd)
raster_Tmean_annual=raster(idw_Tmean_annual)
save(raster_Tmean_annual,file="raster_Tmean_current")


coordinates(Tmean)= ~long + Lat
idw_j<-gstat::idw(tmean~1,locations=subset(Tmean,month==1),newdata=grd)
idw_j <-raster(idw_j)
idw_f<-gstat::idw(tmean~1,locations=subset(Tmean,month==2),newdata=grd)
idw_f <-raster(idw_f)
idw_m<-gstat::idw(tmean~1,locations=subset(Tmean,month==3),newdata=grd)
idw_m <-raster(idw_m)
idw_a<-gstat::idw(tmean~1,locations=subset(Tmean,month==4),newdata=grd)
idw_a <-raster(idw_a)
idw_ma<-gstat::idw(tmean~1,locations=subset(Tmean,month==5),newdata=grd)
idw_ma <-raster(idw_ma)
idw_ju<-gstat::idw(tmean~1,locations=subset(Tmean,month==6),newdata=grd)
idw_ju <-raster(idw_ju)
idw_jl<-gstat::idw(tmean~1,locations=subset(Tmean,month==7),newdata=grd)
idw_jl <-raster(idw_jl)
idw_au<-gstat::idw(tmean~1,locations=subset(Tmean,month==8),newdata=grd)
idw_au <-raster(idw_au)
idw_s<-gstat::idw(tmean~1,locations=subset(Tmean,month==9),newdata=grd)
idw_s <-raster(idw_s)
idw_o<-gstat::idw(tmean~1,locations=subset(Tmean,month==10),newdata=grd)
idw_o <-raster(idw_o)
idw_n<-gstat::idw(tmean~1,locations=subset(Tmean,month==11),newdata=grd)
idw_n <-raster(idw_n)
idw_d<-gstat::idw(tmean~1,locations=subset(Tmean,month==12),newdata=grd)
idw_d <-raster(idw_d)
stack_Tmean=stack(idw_j,
                       idw_f,
                       idw_m,
                       idw_a,
                       idw_ma,
                       idw_ju,
                       idw_jl,
                       idw_au,
                       idw_s,
                       idw_o,
                       idw_n,
                       idw_d
                       )

#save(stack_Tmax_histor,file="stack_Tmax_historico")
save(stack_Tmean,file="stack_Tmean_current")
```



Interpolation Tmin 1950-2000

```{R}
load('monthly_Tmin_1950_2000_By_station_objB')
Tmin2=as.data.frame(cbind(Tmin,rep(seq(1,dim(Tmin)[1]/12,1),each=12)))
colnames(Tmin2)[5]="station"

T2<-aggregate(tmin  ~ station, data=Tmin2,FUN=mean,simplify=F)


T3=as.data.frame(cbind(subset(Tmin,month==1)$long[-length(subset(Tmin,month==1)$long)],subset(Tmin,month==1)$Lat[-length(subset(Tmean,month==1)$Lat)],as.vector(unlist(T2$tmin))))

colnames(T3)=c("long","Lat","tm")

coordinates(T3)= ~long + Lat
idw_Tmin_annual<-gstat::idw(tm~1,locations=T3,newdata=grd)
raster_Tmin_annual=raster(idw_Tmin_annual)
save(raster_Tmin_annual,file="raster_Tmin_current")

```