require(raster)
require(MASS)
require(ncdf4)
require(magrittr)

source("Estimation.R")
source("Estimation_past.R")
source("future_scenarios.R")
source("get_climate_scenarios.R")
source("combined_distribution.R")
#source("get_species_presence_function.R")
